### ISSUE TITLE
update how day_length is calculated in the analysis

### ISSUE THREAD

**Issue by kalebentley** [wdfw-fp/CreelEstimates#15]
Problem: The current calculation of day length in the analysis is based on sunrise and sunrise, which doesn't match legal fishing hours (e.g., night closures; see below)

Solution:  .We need to add more flexibility in defining day length in the analysis (i.e., don't just default it to being sunrise to sunset).  

More information:  Overall, day length should match either legal fishing hours or the hours that our creel survey covered (or that we assume it covers).  Based on our fishing regs, fisheries are open 24 hours unless other denotes in the special rules sections.  Many fisheries institute a “night closure”, which allows fishing one hour before sunrise and one hour after sunset.  Therefore, if a fishery has a “night closure” rule, the day length in the analysis should be sunrise to sunset (in hours) plus two.  In the latest version of my Creel Schedule Generator, I have added flexibility in defining day length which defines the potential within day sampling frame for each date.  For fisheries that do not have a night closure specified, in most cases, I am still using the night closures sample frame as I have assumed that we are not sending staff out into the night to sample fisheries.  This implicitly assumes there is zero fishing effort and catch during the night.  We can revisit this assumption as needed.  In the past, I have set up schedules that have "other" within day sampling frame (i.e., day lengths in the analysis).  For instance, there are a set of reservoirs down in the lower Columbia that have a small number of parking lots that are gated and the gates don't open until 7 AM (independent of sunrise).

**Comment by evanbooher** [comment]
Functionality for fishery-specific day length choices (e.g., night closure, sunrise / sunset, fix time) added to script.
