### ISSUE TITLE
managing fishery closure data

### ISSUE THREAD

**Issue by kalebentley** [wdfw-fp/CreelEstimates#21]
The current PE and BSS analysis manage fishery closure data through a standalone, fishery-specific look-up table (lut) saved as a .csv in the input_files sub-folder.  Specifically, this file lists all dates (rows) and sections (columns) for the fishery and denotes whether the fishery was open or closed by entering TRUE or FALSE, respectively.  
As we move to update/merge the PE and BSS scripts, we (@daauerbach & @evanbooher) have decided that instead of having many, fishery-specific closure_luts - let's create a single "master" closure_lut that will be normalized using three columns: fishery_name, date, and section.  
To expedite this change, this new "master" lut will be a  single .csv file located in the input_files sub-folder.  The biggest question mark with this approach (and potential limitation) will be multiple users editing this single .csv file (simultaneously) and making sure it is updated via GitHub. 
A medium-term solution will be creating a database input interface will @dannyjwarren created to manage/update fishery names and locations.  A long-term solution for managing and querying closures will be leveraging a regulations database (timeline unknown; many other issues to line out here).  Somewhere between our short- and medium-term solution, we can reassess input structure to make managing/entering closure data easier on users.
To close this issue - the following tasks need to be completed:

1.  create the new "master" closures lut,
2.  transfer data from individaul fishery-specific closure luts to master file
3. update data wrangling code to import new closure lut and re-generate closure object(s) for analysis.  
4. ensure that our modification of the closure luts is in line with how we've chosen to modify start and end dates of the fishery (which used to be denoted via the closures lut)

**Comment by evanbooher** [comment]
All of these tasks are complete, including color coding of closure dates in "days" table object in knitted html.
