### ISSUE TITLE
Include interview$zip_code column in fetch_dwg

### ISSUE THREAD

**Issue by ctholley** [wdfw-fp/CreelEstimates#37]
https://github.com/wdfw-fp/CreelEstimates/blob/178ac20b19c406e9bb4cf0e91a6d5f2f959caf3f/R_functions/fetch_dwg.R#L35-L45

Could we include the zip_code column (and maybe state_residence) in the dwg object instead of removing it with `select()` on line 45? I'm working on creating some maps of angler distribution and would like to work this into my in-season update template workflow.

For example:
![image](https://github.com/wdfw-fp/CreelEstimates/assets/62571975/311efb63-2c4c-4b53-bdd0-0e8e4cc2d644)

**Comment by evanbooher** [comment]
Fields now available in dwg$interview
